server:
  port: 8902

eureka:
  client:
    # Pull down a local copy of the registry
    fetchRegistry: true
    healthcheck:
      enabled: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    # Register the IP of the service rather than the server name (useful when there is no a
    # server-based environment where a service is assigned a DNS-backed host name, usually in Docker for example)
    preferIpAddress: true

springfox:
  documentation:
    swagger:
      v2:
        # Api docs path properties
        path: /authentication/v2/api-docs




### MOVE TO Config-server files ###
spring:
  ## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: microservice
    # Using environment variable ENCRYPT_KEY=ENCRYPT_KEY
    # Getting the value with POST localhost:8888/encrypt and the password in its body
    # Raw password: microservice
    password: "{cipher}c5c54009a56a0f215a208067a2b13189091c13480306c81ab68edfb22a6251ca"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          lob:
            # With Java >= 9, to avoid:
            # SQLFeatureNotSupportedException: Method PgConnection.createClob() is not yet implemented
            non_contextual_creation: true

security:
  jwt:
    token:
      # Http authentication scheme
      authorizationPrefix: 'Bearer '
      signatureAlgorithm: "HMACSHA512"

cache:
  jwtConfiguration:
    entryCapacity: 2
    expireInMinutes: 60
    name: jwtConfigurationCache