server:
  port: 8902

eureka:
  client:
    # Pull down a local copy of the registry
    fetchRegistry: true
    healthcheck:
      enabled: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    # Register the IP of the service rather than the server name (useful when there is no a
    # server-based environment where a service is assigned a DNS-backed host name, usually in Docker for example)
    preferIpAddress: true

springfox:
  documentation:
    swagger:
      v2:
        # Api docs path properties
        path: /security/jwt/v2/api-docs


# TODO: Mirar qué carajo pasa



spring:
  ## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: microservice
    # Using environment variable ENCRYPT_KEY=ENCRYPT_KEY
    # Getting the value with POST localhost:8888/encrypt and the password in its body
    # Raw password: microservice
    password: "microservice"
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          lob:
            # With Java >= 9, to avoid:
            # SQLFeatureNotSupportedException: Method PgConnection.createClob() is not yet implemented
            non_contextual_creation: true
        #naming:
        #  implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        #  physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


security:
  jwe:
    # Raw encryptionSecret: 841d8A6C80C#A4FcAf32D5367t1!C53b
    encryptionSecret: "{cipher}44cb298248eb034715509add03160cb84b9a8095f8f7a1c240125aac4a2080f48ba8b481aac16a12caae1a0983f8c4f7e26ea2da37368f3ed50d8224c029c48e"

cache:
  jwtConfiguration:
    entryCapacity: 2
    expireInSeconds: 3600
    name: jwtConfigurationCache
